"""indice de guias y guia del trabajo

Revision ID: 1dad6a0e64cd
Revises: e81d4b0c9a37
Create Date: 2026-09-29 19:36:20.888942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dad6a0e64cd'
down_revision: Union[str, Sequence[str], None] = 'e81d4b0c9a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carpeta_id', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carpeta_id'], ['library_folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guide_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_file_carpeta_id'), ['carpeta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_file_ruta'), ['ruta'], unique=True)

    with op.batch_alter_table('translation_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guia', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_job', schema=None) as batch_op:
        batch_op.drop_column('guia')

    with op.batch_alter_table('guide_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_file_ruta'))
        batch_op.drop_index(batch_op.f('ix_guide_file_carpeta_id'))

    op.drop_table('guide_file')
    # ### end Alembic commands ###
