"""fase1: library_folder y subtitle_file

Revision ID: 4684c713e94f
Revises:
Create Date: 2026-07-30 21:11:49.269644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4684c713e94f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_folder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ruta", sa.String(), nullable=False),
        sa.Column("ultimo_escaneo", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("library_folder", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_library_folder_ruta"), ["ruta"], unique=True)

    op.create_table(
        "subtitle_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carpeta_id", sa.Integer(), nullable=False),
        sa.Column("ruta", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("formato", sa.Enum("SRT", name="formatosubtitulo"), nullable=False),
        sa.Column(
            "idioma_origen",
            sa.Enum("ES", "EN", "KO", "FR", "DE", "IT", "PT", "JA", "ZH", "UNKNOWN", name="idioma"),
            nullable=False,
        ),
        sa.Column("num_caracteres", sa.Integer(), nullable=False),
        sa.Column("num_bloques", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDING", "TRANSLATED", "ERROR", name="estadosubtitulo"),
            nullable=False,
        ),
        sa.Column("ruta_bilingue", sa.String(), nullable=True),
        sa.Column(
            "idioma_destino",
            sa.Enum("ES", "EN", "KO", "FR", "DE", "IT", "PT", "JA", "ZH", "UNKNOWN", name="idioma"),
            nullable=True,
        ),
        sa.Column("proveedor", sa.String(), nullable=True),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("tamano_bytes", sa.Integer(), nullable=False),
        sa.Column("mensaje_error", sa.String(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["carpeta_id"], ["library_folder.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subtitle_file_carpeta_id"), ["carpeta_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_subtitle_file_estado"), ["estado"], unique=False)
        batch_op.create_index(batch_op.f("ix_subtitle_file_ruta"), ["ruta"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_file_ruta"))
        batch_op.drop_index(batch_op.f("ix_subtitle_file_estado"))
        batch_op.drop_index(batch_op.f("ix_subtitle_file_carpeta_id"))

    op.drop_table("subtitle_file")
    with op.batch_alter_table("library_folder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_library_folder_ruta"))

    op.drop_table("library_folder")
    # ### end Alembic commands ###
